version: "3"
services:
  ntopng:
    build: ./public
    ports:
      - "3000:3000"
    environment:
      REDIS_SERVER: redis:6379
    links:
      - redis
  redis:
    image: redis:6.2-alpine